PRAGMA foreign_keys=off;
BEGIN TRANSACTION;
DELETE FROM candidates WHERE J IS NOT 'PREFEITO';
ALTER TABLE candidates RENAME TO x_candidates;
CREATE TABLE candidates (

	cid INTEGER PRIMARY KEY,
	A TEXT,
	B TEXT,
	ANO_ELEICAO TEXT,
	NUM_TURNO TEXT,
	E TEXT,
	SIGLA_UF TEXT,
	SIGLA_UE TEXT,
	DESCRICAO_UE TEXT,
	CODIGO_CARGO TEXT,
	DESCRICAO_CARGO TEXT,
	NOME_CANDIDATO TEXT,
	SEQUENCIAL_CANDIDATO TEXT,
	NUMERO_CANDIDATO TEXT,
	CPF_CANDIDATO TEXT,
	NOME_URNA_CANDIDATO TEXT,
	P TEXT,
	Q TEXT,
	NUMERO_PARTIDO TEXT,
	SIGLA_PARTIDO TEXT,
	NOME_PARTIDO TEXT,
	CODIGO_LEGENDA TEXT,
	SIGLA_LEGENDA TEXT,
	COMPOSICAO_LEGENDA TEXT,
	NOME_LEGENDA TEXT,
	CODIGO_OCUPACAO TEXT,
	DESCRICAO_OCUPACAO TEXT,
	AA TEXT,
	NUM_TITULO_ELEITORAL_CANDIDATO TEXT,
	IDADE_DATA_ELEICAO TEXT,
	CODIGO_SEXO TEXT,
	AE TEXT,
	AF TEXT,
	AG TEXT,
	AH TEXT,
	AI TEXT,
	AJ TEXT,
	AK TEXT,
	AL TEXT,
	AM TEXT,
	AN TEXT,
	DESPESA_MAX_CAMPANHA TEXT,
	COD_SIT_TOT_TURNO TEXT,
	DESC_SIT_TOT_TURNO TEXT,
	NM_EMAIL TEXT,
	url TEXT,
	pdf TEXT,
	txt TEXT

);

INSERT INTO candidates (
	A, B, ANO_ELEICAO, NUM_TURNO, E, SIGLA_UF, SIGLA_UE, DESCRICAO_UE, CODIGO_CARGO, DESCRICAO_CARGO, NOME_CANDIDATO, SEQUENCIAL_CANDIDATO, NUMERO_CANDIDATO, CPF_CANDIDATO, NOME_URNA_CANDIDATO, P, Q, NUMERO_PARTIDO, SIGLA_PARTIDO, NOME_PARTIDO, CODIGO_LEGENDA, SIGLA_LEGENDA,
	COMPOSICAO_LEGENDA, NOME_LEGENDA, CODIGO_OCUPACAO, DESCRICAO_OCUPACAO, AA, NUM_TITULO_ELEITORAL_CANDIDATO, IDADE_DATA_ELEICAO, CODIGO_SEXO, AE, AF, AG, AH, AI, AJ, AK, AL, AM,
	AN, DESPESA_MAX_CAMPANHA, COD_SIT_TOT_TURNO, DESC_SIT_TOT_TURNO, NM_EMAIL )
SELECT
	A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V,
	W, X, Y, Z, AA, AB, AC, AD, AE, AF, AG, AH, AI, AJ, AK, AL, AM,
	AN, AO, AP, AQ, AR
FROM x_candidates;

DROP TABLE x_candidates;
COMMIT;
PRAGMA foreign_keys=on;


